import { z } from 'zod';

/**
 * Validates the request body for creating a new employee.
 * Spec: name (required), email (required, valid format).
 * ID is auto-generated by the database.
 */
export const createEmployeeSchema = z.object({
  name: z.string().min(1, 'Name is required').max(255),
  email: z.string().email('Invalid email format').max(255),
});

export type CreateEmployeeInput = z.infer<typeof createEmployeeSchema>;
